# Generated by Django 2.0.2 on 2018-02-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('registeration_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
