# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180228_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='selected_education',
            field=models.CharField(default='Default', max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='university_branch',
            field=models.CharField(default='Default', max_length=250),
        ),
    ]
